# Generated by Django 3.0 on 2019-12-29 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_custm_user_sxj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custm_user',
            name='sxj',
        ),
    ]
