# Generated by Django 3.0 on 2019-12-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_custm_user_sxj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custm_user',
            name='createTime',
        ),
        migrations.AddField(
            model_name='custm_user',
            name='lastUpdatedTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
